pipeline{
    agent{ label 'slave1'}

    stage {

        stage ('Apply Service'){
            steps {
                sh "kubectl apply -f kubernetes/service.yaml"
            }
        }
        stage ('Apply Deployment'){
            steps {
                sh 'kubectl apply -f kubernetes/deploy.yaml'
            }
        }
    }
}