apiVersion: v1
kind: Service
metadata:
  name: us-service

  labels:
    app: us-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: us-service
status:
  loadbalancer: {}
